#!/usr/bin/env python3
"""Rebuild prices.json from LiteLLM's live, community-maintained price database.

Usage:
  python update_prices.py            refresh prices for all models already tracked
  python update_prices.py NAME ...   also add these model ids

Prices are USD per 1 million tokens. Standard library only.
"""

import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ("https://raw.githubusercontent.com/BerriAI/litellm/main/"
          "model_prices_and_context_window.json")
PREFIXES = ["", "gemini/", "openai/", "anthropic/", "vertex_ai/", "openrouter/"]


def wanted_models():
    models = set()
    prices_file = ROOT / "prices.json"
    if prices_file.exists():
        old = json.loads(prices_file.read_text(encoding="utf-8"))
        models.update(k for k in old if not k.startswith("_"))
    for name in ("official", "community"):
        f = ROOT / "data" / f"{name}.json"
        if f.exists():
            for entry in json.loads(f.read_text(encoding="utf-8")):
                models.add(entry["model"])
    models.update(sys.argv[1:])
    return sorted(models)


def main():
    print(f"Fetching {SOURCE} ...")
    with urllib.request.urlopen(SOURCE, timeout=120) as resp:
        db = json.loads(resp.read().decode("utf-8"))

    out = {"_comment": "USD per 1 million tokens. Auto-generated by update_prices.py "
                       "from LiteLLM's price database; edit only to override."}
    misses = []
    for model in wanted_models():
        hit = None
        for prefix in PREFIXES:
            entry = db.get(prefix + model)
            if entry and "input_cost_per_token" in entry and "output_cost_per_token" in entry:
                hit = entry
                break
        if hit:
            out[model] = {
                "in": round(hit["input_cost_per_token"] * 1e6, 4),
                "out": round(hit["output_cost_per_token"] * 1e6, 4),
            }
            print(f"  {model}: in ${out[model]['in']}/M, out ${out[model]['out']}/M")
        else:
            misses.append(model)

    (ROOT / "prices.json").write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Wrote prices.json with {len(out) - 1} model(s).")
    if misses:
        print("Not found in the price database (add them to prices.json by hand):")
        for m in misses:
            print(f"  {m}")


if __name__ == "__main__":
    main()
